version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/cumulus-message-adapter
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{ { checksum "package.json" }}
      - run:
          name: Run tests
          command: |
            sudo apt update && sudo apt install libssl-dev libffi-dev zlib1g-dev
            wget -c https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tgz
            tar zxf Python-3.10.9.tgz
            cd Python-3.10.9
            sudo ./configure --enable-optimizations
            sudo make -j4
            sudo make altinstall
            sudo update-alternatives --install /usr/bin/python python /usr/local/bin/python3.10 1
            sudo npm install -g npm@8.6.0 && npm install
            npm run build
            npm run lint
            npm run test
      - persist_to_workspace:
          root: ./
          paths:
            - dist
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
  publish:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/cumulus-message-adapter
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - "a0:b7:39:23:35:54:e5:36:ef:b1:9c:5c:22:ec:e2:26"
      - run:
          name: Publish release
          command: |
            GITHUB_TOKEN=${GITHUB_TOKEN} sh bin/release.sh
      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            npm publish || echo 'npm publishing failed'

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
